In [4]:
import numpy as np

Problem #1

In [2]:
def n_size_ndarray_creation(n, dtype=np.int):
    X = np.arange(n*n).reshape(n,n)
    return X

In [3]:
print(n_size_ndarray_creation(5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Problem #2

In [17]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    if type == 0:
        return np.zeros(shape=shape, dtype=int)
    elif type == 1:
        return np.ones(shape=shape, dtype=int)
    elif type == 99:
        return np.empty(shape=shape, dtype=int)
    else:
        return print("잘못된 type입니다.")

In [20]:
zero_or_one_or_empty_ndarray(shape=(3,3), type=1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
zero_or_one_or_empty_ndarray(shape=(3,3), type=99)

array([[ -105225128,         530, -1001348880],
       [      32762,           2,           0],
       [         -1,          -1,  1761607680]])

Problem #3

In [60]:
def change_shape_of_ndarray(X, n_row):
    if n_row == 1:
        return X.flatten()
    else:
        return X.reshape(n_row, -1)

In [61]:
X = np.ones((32,32), dtype=np.int)

In [62]:
change_shape_of_ndarray(X, 1)

array([1, 1, 1, ..., 1, 1, 1])

In [63]:
change_shape_of_ndarray(X, 512)

array([[1, 1],
       [1, 1],
       [1, 1],
       ...,
       [1, 1],
       [1, 1],
       [1, 1]])

Problem #4

In [94]:
def concat_ndarray(X_1, X_2, axis):
    if X_1.ndim == 1:
        X_1 = X_1.reshape(1, -1)
    if X_2.ndim == 1:
        X_2 = X_2.reshape(1, -1)

    try:
        return np.concatenate((X_1,X_2), axis=axis)
    except ValueError as e:
        return False

In [95]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [96]:
concat_ndarray(a, b, 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
concat_ndarray(a, b, 1)

False

In [98]:
a = np.array([1, 2])
b = np.array([5, 6, 7])

In [99]:
concat_ndarray(a, b, 1)

array([[1, 2, 5, 6, 7]])

In [100]:
concat_ndarray(a, b, 0)

False

Problem #5

In [26]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    if axis == 0:
        mean = X.mean(axis = axis)
        std = X.std(axis = axis)
        Z = (X - mean) / std
        return Z
    elif axis == 1:
        mean = X.mean(axis = axis).reshape(-1, 1)
        std = X.std(axis = axis).reshape(-1, 1)
        Z = (X - mean) / std
        # Z = ((X.T) - X.mean(axis=1)) / X.std(axis=1).T
        return Z
    elif axis == 99:
        mean = X.mean()
        std = X.std()
        Z = (X - mean) / std
        return Z
    else:
        return print("잘못된 axis입니다.")

In [27]:
X = np.arange(12, dtype=np.float32).reshape(6,2)

In [28]:
normalize_ndarray(X)

array([[-1.593255  , -1.3035723 ],
       [-1.0138896 , -0.7242068 ],
       [-0.4345241 , -0.14484136],
       [ 0.14484136,  0.4345241 ],
       [ 0.7242068 ,  1.0138896 ],
       [ 1.3035723 ,  1.593255  ]], dtype=float32)

In [29]:
normalize_ndarray(X, 1)

array([[-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.]], dtype=float32)

In [30]:
normalize_ndarray(X, 0)

array([[-1.46385, -1.46385],
       [-0.87831, -0.87831],
       [-0.29277, -0.29277],
       [ 0.29277,  0.29277],
       [ 0.87831,  0.87831],
       [ 1.46385,  1.46385]], dtype=float32)

Problem #6

In [31]:
def save_ndarray(X, filename="test.npy"):
    return np.save(filename, X)

In [32]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)
filename = "test.npy"
save_ndarray(X, filename) #test.npy 파일이 생성됨
# np.load("test.npy") # 파일 읽는 것

Problem #7

In [33]:
def boolean_index(X, condition):
    condition = eval(str("X") + condition)
    return np.where(condition)

In [34]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)
boolean_index(X, "== 3")

(array([0], dtype=int64), array([3], dtype=int64))

In [36]:
X = np.arange(32, dtype=np.float32)
boolean_index(X, "> 6")

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31], dtype=int64),)

Problem #8

In [45]:
def find_nearest_value(X, target_value):
    return X[np.argmin(abs(X - target_value))]

In [46]:
X = np.random.uniform(0, 1, 100)
target_value = 0.3
find_nearest_value(X, target_value)

0.2936795316339743

Problem #9

In [51]:
def get_n_largest_values(X, n):
    return np.sort(X)[::-1][:n]

In [52]:
X = np.random.uniform(0, 1, 100)

In [53]:
get_n_largest_values(X, 3)

array([0.99300868, 0.98974806, 0.96390201])

In [54]:
get_n_largest_values(X, 5)

array([0.99300868, 0.98974806, 0.96390201, 0.95880708, 0.95170948])